-- Schema of the Electronic Conspicuity Monitor, generated by tools/schema_doc.py on 2026-10-09
-- from the production database `ads_l` (MariaDB 10.11.18-MariaDB-0+deb12u1), code at ce5983f.
-- Do not edit: change the database through a dated file in schema/, then run
--   cd ~/ads-l-map && python3 tools/schema_doc.py --out ~/schemadoc
-- and commit this file and SCHEMA.md as it writes them. SCHEMA.md says what each
-- table holds and which code reads and writes it.
--
-- Each table as SHOW CREATE TABLE gives it, with IF NOT EXISTS added and the
-- AUTO_INCREMENT counter removed. Load it on an empty server with
--   mysql < schema.sql
-- then create the service user and its grants as README.md describes.

CREATE DATABASE IF NOT EXISTS ads_l CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci;
USE ads_l;

CREATE TABLE IF NOT EXISTS `daily_agl_hours` (
  `day` date NOT NULL,
  `kind` varchar(16) NOT NULL,
  `terrain` varchar(8) NOT NULL DEFAULT '',
  `solar_hour` tinyint(3) unsigned NOT NULL,
  `agl_band` tinyint(3) unsigned NOT NULL,
  `air_seconds` double NOT NULL DEFAULT 0,
  PRIMARY KEY (`day`,`kind`,`terrain`,`solar_hour`,`agl_band`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

CREATE TABLE IF NOT EXISTS `daily_air_cells` (
  `day` date NOT NULL,
  `kind` varchar(12) NOT NULL,
  `lat_idx` smallint(6) NOT NULL,
  `lon_idx` smallint(6) NOT NULL,
  `air_seconds` double NOT NULL DEFAULT 0,
  `aircraft` int(10) unsigned NOT NULL DEFAULT 0,
  PRIMARY KEY (`day`,`kind`,`lat_idx`,`lon_idx`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

CREATE TABLE IF NOT EXISTS `daily_circling` (
  `day` date NOT NULL,
  `category` tinyint(3) unsigned NOT NULL,
  `thermals_right` int(10) unsigned NOT NULL DEFAULT 0,
  `thermals_left` int(10) unsigned NOT NULL DEFAULT 0,
  `degrees_right` double NOT NULL DEFAULT 0,
  `degrees_left` double NOT NULL DEFAULT 0,
  `seconds_right` double NOT NULL DEFAULT 0,
  `seconds_left` double NOT NULL DEFAULT 0,
  `aircraft` int(10) unsigned NOT NULL DEFAULT 0,
  PRIMARY KEY (`day`,`category`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

CREATE TABLE IF NOT EXISTS `daily_circling_pilot` (
  `day` date NOT NULL,
  `address` varchar(16) NOT NULL,
  `category` tinyint(3) unsigned NOT NULL,
  `right_hand` int(10) unsigned NOT NULL DEFAULT 0,
  `left_hand` int(10) unsigned NOT NULL DEFAULT 0,
  PRIMARY KEY (`day`,`address`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

CREATE TABLE IF NOT EXISTS `daily_circling_time` (
  `day` date NOT NULL,
  `kind` varchar(16) NOT NULL,
  `terrain` varchar(8) NOT NULL DEFAULT '',
  `solar_hour` tinyint(3) unsigned NOT NULL,
  `circling_seconds` double NOT NULL DEFAULT 0,
  `air_seconds` double NOT NULL DEFAULT 0,
  PRIMARY KEY (`day`,`kind`,`terrain`,`solar_hour`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

CREATE TABLE IF NOT EXISTS `daily_crewed_encounters` (
  `day` date NOT NULL,
  `kind_a` varchar(12) NOT NULL,
  `kind_b` varchar(12) NOT NULL,
  `threshold` varchar(5) NOT NULL,
  `lat_idx` smallint(6) NOT NULL DEFAULT -32768,
  `lon_idx` smallint(6) NOT NULL DEFAULT -32768,
  `distance_band` tinyint(3) unsigned NOT NULL,
  `closing_band` tinyint(3) unsigned NOT NULL,
  `geometry` tinyint(3) unsigned NOT NULL DEFAULT 255,
  `systems_a` varchar(255) NOT NULL,
  `systems_b` varchar(255) NOT NULL,
  `shares_radio` tinyint(1) NOT NULL,
  `shares_any` tinyint(1) NOT NULL,
  `encounters` int(10) unsigned NOT NULL DEFAULT 0,
  PRIMARY KEY (`day`,`kind_a`,`kind_b`,`threshold`,`lat_idx`,`lon_idx`,`distance_band`,`closing_band`,`geometry`,`systems_a`,`systems_b`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

CREATE TABLE IF NOT EXISTS `daily_cruise` (
  `day` date NOT NULL,
  `kind` varchar(12) NOT NULL,
  `emitter` varchar(6) NOT NULL,
  `altitude_ref` varchar(8) NOT NULL,
  `altitude_band` tinyint(3) unsigned NOT NULL,
  `speed_band` tinyint(3) unsigned NOT NULL,
  `segments` int(10) unsigned NOT NULL DEFAULT 0,
  `seconds` double NOT NULL DEFAULT 0,
  `aircraft` int(10) unsigned NOT NULL DEFAULT 0,
  PRIMARY KEY (`day`,`kind`,`emitter`,`altitude_ref`,`altitude_band`,`speed_band`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

CREATE TABLE IF NOT EXISTS `daily_drone_cells` (
  `day` date NOT NULL,
  `evidence` tinyint(3) unsigned NOT NULL DEFAULT 2,
  `flight_class` tinyint(3) unsigned NOT NULL DEFAULT 0,
  `lat_idx` smallint(6) NOT NULL,
  `lon_idx` smallint(6) NOT NULL,
  `air_seconds` double NOT NULL DEFAULT 0,
  `aircraft` int(10) unsigned NOT NULL DEFAULT 0,
  PRIMARY KEY (`day`,`evidence`,`flight_class`,`lat_idx`,`lon_idx`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

CREATE TABLE IF NOT EXISTS `daily_drone_classes` (
  `day` date NOT NULL,
  `evidence` tinyint(3) unsigned NOT NULL,
  `flight_class` tinyint(3) unsigned NOT NULL DEFAULT 0,
  `addresses` int(10) unsigned NOT NULL DEFAULT 0,
  `air_seconds` double NOT NULL DEFAULT 0,
  PRIMARY KEY (`day`,`evidence`,`flight_class`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

CREATE TABLE IF NOT EXISTS `daily_drone_encounters` (
  `day` date NOT NULL,
  `evidence` tinyint(3) unsigned NOT NULL DEFAULT 2,
  `flight_class` tinyint(3) unsigned NOT NULL DEFAULT 0,
  `lat_idx` smallint(6) NOT NULL DEFAULT -32768,
  `lon_idx` smallint(6) NOT NULL DEFAULT -32768,
  `drone_systems` varchar(255) NOT NULL,
  `other_category` tinyint(3) unsigned NOT NULL,
  `other_systems` varchar(255) NOT NULL,
  `distance_band` tinyint(3) unsigned NOT NULL,
  `closing_band` tinyint(3) unsigned NOT NULL DEFAULT 255,
  `geometry` tinyint(3) unsigned NOT NULL DEFAULT 255,
  `shared_system` tinyint(1) NOT NULL,
  `encounters` int(10) unsigned NOT NULL DEFAULT 0,
  PRIMARY KEY (`day`,`evidence`,`flight_class`,`lat_idx`,`lon_idx`,`drone_systems`,`other_category`,`other_systems`,`distance_band`,`closing_band`,`geometry`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

CREATE TABLE IF NOT EXISTS `daily_drone_extent` (
  `day` date NOT NULL,
  `evidence` tinyint(3) unsigned NOT NULL DEFAULT 2,
  `flight_class` tinyint(3) unsigned NOT NULL DEFAULT 0,
  `extent_band` tinyint(3) unsigned NOT NULL,
  `drones` int(10) unsigned NOT NULL DEFAULT 0,
  PRIMARY KEY (`day`,`evidence`,`flight_class`,`extent_band`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

CREATE TABLE IF NOT EXISTS `daily_drones` (
  `day` date NOT NULL,
  `evidence` tinyint(3) unsigned NOT NULL DEFAULT 2,
  `flight_class` tinyint(3) unsigned NOT NULL DEFAULT 0,
  `lat_idx` smallint(6) NOT NULL,
  `lon_idx` smallint(6) NOT NULL,
  `height_band` tinyint(3) unsigned NOT NULL,
  `speed_band` tinyint(3) unsigned NOT NULL,
  `systems` varchar(255) NOT NULL,
  `air_seconds` double NOT NULL DEFAULT 0,
  `aircraft` int(10) unsigned NOT NULL DEFAULT 0,
  PRIMARY KEY (`day`,`evidence`,`flight_class`,`lat_idx`,`lon_idx`,`height_band`,`speed_band`,`systems`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

CREATE TABLE IF NOT EXISTS `daily_flight_classes` (
  `day` date NOT NULL,
  `kind` varchar(16) NOT NULL,
  `terrain` varchar(8) NOT NULL,
  `class` varchar(16) NOT NULL,
  `landing` varchar(8) NOT NULL,
  `distance_band` tinyint(3) unsigned NOT NULL,
  `path_band` tinyint(3) unsigned NOT NULL,
  `flights` int(10) unsigned NOT NULL DEFAULT 0,
  PRIMARY KEY (`day`,`kind`,`terrain`,`class`,`landing`,`distance_band`,`path_band`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

CREATE TABLE IF NOT EXISTS `daily_flights` (
  `day` date NOT NULL,
  `kind` varchar(16) NOT NULL,
  `terrain` varchar(8) NOT NULL DEFAULT '',
  `launch` varchar(12) NOT NULL DEFAULT '',
  `start_hour` tinyint(3) unsigned NOT NULL,
  `duration_band` tinyint(3) unsigned NOT NULL,
  `extent_band` tinyint(3) unsigned NOT NULL,
  `path_band` tinyint(3) unsigned NOT NULL,
  `flights` int(10) unsigned NOT NULL DEFAULT 0,
  `seconds` double NOT NULL DEFAULT 0,
  `path_m` double NOT NULL DEFAULT 0,
  PRIMARY KEY (`day`,`kind`,`terrain`,`launch`,`start_hour`,`duration_band`,`extent_band`,`path_band`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

CREATE TABLE IF NOT EXISTS `daily_gaggles` (
  `day` date NOT NULL,
  `category_a` tinyint(3) unsigned NOT NULL,
  `category_b` tinyint(3) unsigned NOT NULL,
  `same_side` int(10) unsigned NOT NULL DEFAULT 0,
  `opposite_side` int(10) unsigned NOT NULL DEFAULT 0,
  PRIMARY KEY (`day`,`category_a`,`category_b`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

CREATE TABLE IF NOT EXISTS `daily_helicopter_night` (
  `day` date NOT NULL,
  `lat_idx` smallint(6) NOT NULL,
  `lon_idx` smallint(6) NOT NULL,
  `night` tinyint(1) NOT NULL,
  `agl_band` tinyint(3) unsigned NOT NULL,
  `air_seconds` double NOT NULL DEFAULT 0,
  `aircraft` int(10) unsigned NOT NULL DEFAULT 0,
  PRIMARY KEY (`day`,`lat_idx`,`lon_idx`,`night`,`agl_band`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

CREATE TABLE IF NOT EXISTS `daily_hours_solar` (
  `day` date NOT NULL,
  `local_date` date NOT NULL,
  `category` tinyint(3) unsigned NOT NULL,
  `solar_hour` tinyint(3) unsigned NOT NULL,
  `air_seconds` double NOT NULL DEFAULT 0,
  `aircraft` int(10) unsigned NOT NULL DEFAULT 0,
  PRIMARY KEY (`day`,`local_date`,`category`,`solar_hour`),
  KEY `idx_local_date` (`local_date`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

CREATE TABLE IF NOT EXISTS `daily_launches` (
  `day` date NOT NULL,
  `method` varchar(12) NOT NULL,
  `towed_kind` varchar(12) NOT NULL,
  `terrain` varchar(8) NOT NULL DEFAULT '',
  `lat_idx` smallint(6) NOT NULL,
  `lon_idx` smallint(6) NOT NULL,
  `height_band` tinyint(3) unsigned NOT NULL,
  `duration_band` tinyint(3) unsigned NOT NULL,
  `launches` int(10) unsigned NOT NULL DEFAULT 0,
  PRIMARY KEY (`day`,`method`,`towed_kind`,`terrain`,`lat_idx`,`lon_idx`,`height_band`,`duration_band`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

CREATE TABLE IF NOT EXISTS `daily_mixed_thermals` (
  `day` date NOT NULL,
  `kind_a` varchar(16) NOT NULL,
  `kind_b` varchar(16) NOT NULL,
  `vsep_band` tinyint(3) unsigned NOT NULL,
  `thermals` int(10) unsigned NOT NULL DEFAULT 0,
  PRIMARY KEY (`day`,`kind_a`,`kind_b`,`vsep_band`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

CREATE TABLE IF NOT EXISTS `daily_parked` (
  `day` date NOT NULL,
  `system_name` varchar(32) NOT NULL,
  `category` tinyint(3) unsigned NOT NULL,
  `aircraft` int(10) unsigned NOT NULL DEFAULT 0,
  `seconds` double NOT NULL DEFAULT 0,
  `packets` int(10) unsigned NOT NULL DEFAULT 0,
  PRIMARY KEY (`day`,`system_name`,`category`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

CREATE TABLE IF NOT EXISTS `daily_quality` (
  `day` date NOT NULL,
  `scope` enum('system','receiver') NOT NULL,
  `name` varchar(64) NOT NULL,
  `check_name` varchar(64) NOT NULL,
  `count` int(10) unsigned NOT NULL DEFAULT 0,
  `total` int(10) unsigned NOT NULL DEFAULT 0,
  `value` double DEFAULT NULL,
  PRIMARY KEY (`day`,`scope`,`name`,`check_name`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

CREATE TABLE IF NOT EXISTS `daily_routes` (
  `day` date NOT NULL,
  `airfield_a` varchar(255) NOT NULL,
  `airfield_b` varchar(255) NOT NULL,
  `address` varchar(16) NOT NULL,
  `flights` int(10) unsigned NOT NULL DEFAULT 0,
  PRIMARY KEY (`day`,`airfield_a`,`airfield_b`,`address`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

CREATE TABLE IF NOT EXISTS `daily_same_aircraft_pairs` (
  `day` date NOT NULL,
  `kind_a` varchar(12) NOT NULL,
  `kind_b` varchar(12) NOT NULL,
  `threshold` varchar(5) NOT NULL,
  `pairs` int(10) unsigned NOT NULL DEFAULT 0,
  `encounters` int(10) unsigned NOT NULL DEFAULT 0,
  PRIMARY KEY (`day`,`kind_a`,`kind_b`,`threshold`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

CREATE TABLE IF NOT EXISTS `daily_thermal_sites` (
  `day` date NOT NULL,
  `kind` varchar(16) NOT NULL,
  `lat_idx` smallint(6) NOT NULL,
  `lon_idx` smallint(6) NOT NULL,
  `site` varchar(255) NOT NULL,
  `thermals` int(10) unsigned NOT NULL DEFAULT 0,
  PRIMARY KEY (`day`,`kind`,`lat_idx`,`lon_idx`,`site`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

CREATE TABLE IF NOT EXISTS `daily_thermals` (
  `day` date NOT NULL,
  `kind` varchar(16) NOT NULL,
  `terrain` varchar(8) NOT NULL DEFAULT '',
  `solar_hour` tinyint(3) unsigned NOT NULL,
  `lat_idx` smallint(6) NOT NULL,
  `lon_idx` smallint(6) NOT NULL,
  `climb_band` tinyint(3) unsigned NOT NULL,
  `radius_band` tinyint(3) unsigned NOT NULL,
  `thermals` int(10) unsigned NOT NULL DEFAULT 0,
  `climb_sum` double NOT NULL DEFAULT 0,
  `climbs` int(10) unsigned NOT NULL DEFAULT 0,
  `radius_sum` double NOT NULL DEFAULT 0,
  PRIMARY KEY (`day`,`kind`,`terrain`,`solar_hour`,`lat_idx`,`lon_idx`,`climb_band`,`radius_band`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

CREATE TABLE IF NOT EXISTS `daily_tug_time` (
  `day` date NOT NULL,
  `share_band` tinyint(3) unsigned NOT NULL,
  `tugs` int(10) unsigned NOT NULL DEFAULT 0,
  `tow_seconds` double NOT NULL DEFAULT 0,
  `air_seconds` double NOT NULL DEFAULT 0,
  PRIMARY KEY (`day`,`share_band`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

CREATE TABLE IF NOT EXISTS `daily_tug_tows` (
  `day` date NOT NULL,
  `tows_band` tinyint(3) unsigned NOT NULL,
  `tugs` int(10) unsigned NOT NULL DEFAULT 0,
  PRIMARY KEY (`day`,`tows_band`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

CREATE TABLE IF NOT EXISTS `daily_visibility` (
  `day` date NOT NULL,
  `source` varchar(9) NOT NULL,
  `via` enum('radio','net') NOT NULL,
  `category` tinyint(3) unsigned NOT NULL,
  `flushed_at` datetime NOT NULL,
  `packets` int(10) unsigned NOT NULL,
  `rot_packets` int(10) unsigned NOT NULL,
  `segments` int(10) unsigned NOT NULL,
  `sessions` int(10) unsigned NOT NULL,
  `implausible` int(10) unsigned NOT NULL,
  `air_seconds` double NOT NULL,
  `p0_300` double NOT NULL,
  `p0_1000` double NOT NULL,
  `p0_3000` double NOT NULL,
  `p1_300` double NOT NULL,
  `p1_1000` double NOT NULL,
  `p1_3000` double NOT NULL,
  PRIMARY KEY (`day`,`source`,`via`,`category`,`flushed_at`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

CREATE TABLE IF NOT EXISTS `daily_wave` (
  `day` date NOT NULL,
  `lat_idx` smallint(6) NOT NULL,
  `lon_idx` smallint(6) NOT NULL,
  `climbs` int(10) unsigned NOT NULL DEFAULT 0,
  PRIMARY KEY (`day`,`lat_idx`,`lon_idx`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

CREATE TABLE IF NOT EXISTS `monthly_circling_pilot_summary` (
  `month` char(7) NOT NULL,
  `category` tinyint(3) unsigned NOT NULL,
  `thermal_band` tinyint(3) unsigned NOT NULL,
  `share_decile` tinyint(3) unsigned NOT NULL,
  `pilots` int(10) unsigned NOT NULL,
  PRIMARY KEY (`month`,`category`,`thermal_band`,`share_decile`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

CREATE TABLE IF NOT EXISTS `monthly_circling_preference` (
  `month` char(7) NOT NULL,
  `category` tinyint(3) unsigned NOT NULL,
  `min_thermals` tinyint(3) unsigned NOT NULL,
  `pilots` int(10) unsigned NOT NULL,
  `thermals` int(10) unsigned NOT NULL,
  `right_hand` int(10) unsigned NOT NULL,
  `chance_var_sum` double NOT NULL,
  `share_sum` double NOT NULL,
  `share_sq_sum` double NOT NULL,
  `right_80` int(10) unsigned NOT NULL,
  `left_80` int(10) unsigned NOT NULL,
  `expected_80` double NOT NULL,
  PRIMARY KEY (`month`,`category`,`min_thermals`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

CREATE TABLE IF NOT EXISTS `monthly_devices` (
  `month` char(7) NOT NULL,
  `device_id` varchar(16) NOT NULL,
  `device_type` enum('ADSL','ADSB','FLARM','OTHER') NOT NULL,
  `category` tinyint(3) unsigned DEFAULT NULL,
  `first_seen` datetime NOT NULL,
  PRIMARY KEY (`month`,`device_id`),
  KEY `idx_month_type` (`month`,`device_type`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

CREATE TABLE IF NOT EXISTS `monthly_devices_summary` (
  `month` char(7) NOT NULL,
  `prefix` char(3) NOT NULL,
  `category` tinyint(3) unsigned NOT NULL,
  `devices` int(10) unsigned NOT NULL,
  PRIMARY KEY (`month`,`prefix`,`category`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

CREATE TABLE IF NOT EXISTS `monthly_hours` (
  `month` char(7) NOT NULL,
  `category` tinyint(3) unsigned NOT NULL,
  `segments` double NOT NULL DEFAULT 0,
  `air_seconds` double NOT NULL DEFAULT 0,
  PRIMARY KEY (`month`,`category`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

CREATE TABLE IF NOT EXISTS `monthly_prediction` (
  `month` char(7) NOT NULL,
  `source` varchar(9) NOT NULL,
  `category` tinyint(3) unsigned NOT NULL,
  `horizon` tinyint(3) unsigned NOT NULL,
  `circling` tinyint(3) unsigned NOT NULL,
  `predictor` varchar(20) NOT NULL,
  `b0` double NOT NULL DEFAULT 0,
  `b1` double NOT NULL DEFAULT 0,
  `b2` double NOT NULL DEFAULT 0,
  `b3` double NOT NULL DEFAULT 0,
  `b4` double NOT NULL DEFAULT 0,
  `b5` double NOT NULL DEFAULT 0,
  `b6` double NOT NULL DEFAULT 0,
  `b7` double NOT NULL DEFAULT 0,
  `b8` double NOT NULL DEFAULT 0,
  `b9` double NOT NULL DEFAULT 0,
  `b10` double NOT NULL DEFAULT 0,
  `b11` double NOT NULL DEFAULT 0,
  `b12` double NOT NULL DEFAULT 0,
  `b13` double NOT NULL DEFAULT 0,
  `n` double NOT NULL DEFAULT 0,
  `error_sum` double NOT NULL DEFAULT 0,
  PRIMARY KEY (`month`,`source`,`category`,`horizon`,`circling`,`predictor`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

CREATE TABLE IF NOT EXISTS `monthly_reception_pattern` (
  `month` char(7) NOT NULL,
  `source` varchar(9) NOT NULL,
  `category` tinyint(3) unsigned NOT NULL,
  `dist_band` tinyint(3) unsigned NOT NULL,
  `sector` tinyint(3) unsigned NOT NULL,
  `packets` double NOT NULL DEFAULT 0,
  `snr_sum` double NOT NULL DEFAULT 0,
  `snr_n` double NOT NULL DEFAULT 0,
  PRIMARY KEY (`month`,`source`,`category`,`dist_band`,`sector`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

CREATE TABLE IF NOT EXISTS `monthly_return_summary` (
  `month` char(7) NOT NULL,
  `source` varchar(9) NOT NULL,
  `devices` int(10) unsigned NOT NULL,
  `returned` int(10) unsigned NOT NULL,
  PRIMARY KEY (`month`,`source`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

CREATE TABLE IF NOT EXISTS `monthly_routes_summary` (
  `month` char(7) NOT NULL,
  `airfield_a` varchar(255) NOT NULL,
  `airfield_b` varchar(255) NOT NULL,
  `flights` int(10) unsigned NOT NULL,
  `aircraft` int(10) unsigned NOT NULL,
  PRIMARY KEY (`month`,`airfield_a`,`airfield_b`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

CREATE TABLE IF NOT EXISTS `monthly_snapshot` (
  `month` char(7) NOT NULL,
  `endpoint` varchar(32) NOT NULL,
  `method_commit` char(40) DEFAULT NULL,
  `deployed_commit` char(40) DEFAULT NULL,
  `created_at` datetime NOT NULL,
  `bytes` int(10) unsigned NOT NULL,
  `body` mediumblob NOT NULL,
  PRIMARY KEY (`month`,`endpoint`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

CREATE TABLE IF NOT EXISTS `monthly_sources` (
  `month` char(7) NOT NULL,
  `source` varchar(9) NOT NULL,
  `via` enum('radio','net') NOT NULL,
  `device_id` varchar(16) NOT NULL,
  `category` tinyint(3) unsigned DEFAULT NULL,
  `first_seen` datetime NOT NULL,
  `last_seen` datetime NOT NULL,
  PRIMARY KEY (`month`,`source`,`via`,`device_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

CREATE TABLE IF NOT EXISTS `monthly_sources_summary` (
  `month` char(7) NOT NULL,
  `source` varchar(9) NOT NULL,
  `via` enum('radio','net') NOT NULL,
  `category` tinyint(3) unsigned NOT NULL,
  `devices` int(10) unsigned NOT NULL,
  `multi_day` int(10) unsigned NOT NULL,
  PRIMARY KEY (`month`,`source`,`via`,`category`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

CREATE TABLE IF NOT EXISTS `monthly_systems_combo_summary` (
  `month` char(7) NOT NULL,
  `category` tinyint(3) unsigned NOT NULL,
  `systems` varchar(255) NOT NULL,
  `aircraft` int(10) unsigned NOT NULL,
  PRIMARY KEY (`month`,`category`,`systems`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

CREATE TABLE IF NOT EXISTS `monthly_systems_summary` (
  `month` char(7) NOT NULL,
  `category` tinyint(3) unsigned NOT NULL,
  `one` int(10) unsigned NOT NULL,
  `two` int(10) unsigned NOT NULL,
  `three_or_more` int(10) unsigned NOT NULL,
  `radio_and_phone` int(10) unsigned NOT NULL,
  `phone_only` int(10) unsigned NOT NULL,
  `other_combinations` int(10) unsigned NOT NULL,
  `adsl` int(10) unsigned NOT NULL,
  `adsl_with_flarm` int(10) unsigned NOT NULL,
  `adsl_with_fanet` int(10) unsigned NOT NULL,
  `adsl_only` int(10) unsigned NOT NULL,
  PRIMARY KEY (`month`,`category`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

CREATE TABLE IF NOT EXISTS `monthly_visibility_detail` (
  `month` char(7) NOT NULL,
  `source` varchar(9) NOT NULL,
  `via` enum('radio','net') NOT NULL,
  `category` tinyint(3) unsigned NOT NULL,
  `msl_band` tinyint(3) unsigned NOT NULL,
  `agl_band` tinyint(3) unsigned NOT NULL,
  `segments` double NOT NULL DEFAULT 0,
  `rot_segments` double NOT NULL DEFAULT 0,
  `circling_segments` double NOT NULL DEFAULT 0,
  `air_seconds` double NOT NULL DEFAULT 0,
  `p0_300` double NOT NULL DEFAULT 0,
  `p0_1000` double NOT NULL DEFAULT 0,
  `p0_3000` double NOT NULL DEFAULT 0,
  `p1_300` double NOT NULL DEFAULT 0,
  `p1_1000` double NOT NULL DEFAULT 0,
  `p1_3000` double NOT NULL DEFAULT 0,
  `p2_300` double NOT NULL DEFAULT 0,
  `p2_1000` double NOT NULL DEFAULT 0,
  `p2_3000` double NOT NULL DEFAULT 0,
  `rot_air` double NOT NULL DEFAULT 0,
  `rot_p1_300` double NOT NULL DEFAULT 0,
  `rot_p1_1000` double NOT NULL DEFAULT 0,
  `rot_p2_300` double NOT NULL DEFAULT 0,
  `rot_p2_1000` double NOT NULL DEFAULT 0,
  `circ_air` double NOT NULL DEFAULT 0,
  `circ_p1_300` double NOT NULL DEFAULT 0,
  `circ_p1_1000` double NOT NULL DEFAULT 0,
  `circ_p2_300` double NOT NULL DEFAULT 0,
  `circ_p2_1000` double NOT NULL DEFAULT 0,
  `age_le3` double NOT NULL DEFAULT 0,
  `age_le6` double NOT NULL DEFAULT 0,
  `age_le15` double NOT NULL DEFAULT 0,
  `age_le30` double NOT NULL DEFAULT 0,
  `seg_le3` double NOT NULL DEFAULT 0,
  `seg_le6` double NOT NULL DEFAULT 0,
  `vanish_2` double NOT NULL DEFAULT 0,
  `vanish_5` double NOT NULL DEFAULT 0,
  `vanish_20` double NOT NULL DEFAULT 0,
  `int_le2` double NOT NULL DEFAULT 0,
  `int_le4` double NOT NULL DEFAULT 0,
  `int_le8` double NOT NULL DEFAULT 0,
  `int_le16` double NOT NULL DEFAULT 0,
  `int_le32` double NOT NULL DEFAULT 0,
  `int_le64` double NOT NULL DEFAULT 0,
  `cad_air` double NOT NULL DEFAULT 0,
  `cad_late` double NOT NULL DEFAULT 0,
  `sig_air` double NOT NULL DEFAULT 0,
  `sig_late` double NOT NULL DEFAULT 0,
  PRIMARY KEY (`month`,`source`,`via`,`category`,`msl_band`,`agl_band`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

CREATE TABLE IF NOT EXISTS `monthly_visibility_grid` (
  `month` char(7) NOT NULL,
  `lat_idx` smallint(6) NOT NULL,
  `lon_idx` smallint(6) NOT NULL,
  `grp` varchar(8) NOT NULL,
  `via` enum('radio','net') NOT NULL,
  `segments` double NOT NULL DEFAULT 0,
  `air_seconds` double NOT NULL DEFAULT 0,
  `p0_300` double NOT NULL DEFAULT 0,
  `p1_300` double NOT NULL DEFAULT 0,
  `p1_1000` double NOT NULL DEFAULT 0,
  `p0_1000` double NOT NULL DEFAULT 0,
  `cad_air` double NOT NULL DEFAULT 0,
  `cad_late` double NOT NULL DEFAULT 0,
  `sig_air` double NOT NULL DEFAULT 0,
  `sig_late` double NOT NULL DEFAULT 0,
  PRIMARY KEY (`month`,`lat_idx`,`lon_idx`,`grp`,`via`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

CREATE TABLE IF NOT EXISTS `nightly_runs` (
  `day` date NOT NULL,
  `finished_at` datetime NOT NULL,
  `hours_read` tinyint(3) unsigned NOT NULL,
  `hours_missing` varchar(80) NOT NULL DEFAULT '',
  `line_count` int(10) unsigned NOT NULL,
  `seconds` double NOT NULL,
  `notes` varchar(255) NOT NULL DEFAULT '',
  PRIMARY KEY (`day`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;
