#!/usr/bin/env python3
"""Generate schema.sql and SCHEMA.md from the production database and the code.

    cd ~/ads-l-map && python3 tools/schema_doc.py --out ~/schemadoc

Run on the host, from the service's checkout, as the service user. It reads
the database settings the way nightly.py does (DB_USER and DB_PASSWORD from
the `.env` beside app.py, or ~/.my.cnf without them) and sends the server
nothing but SHOW TABLES, SHOW CREATE TABLE, SHOW GRANTS FOR CURRENT_USER and
SELECTs on information_schema: it reads no row of any table, and no credential
is printed, logged or written. It writes two files into --out, never into the
checkout itself (deploy.sh owns that), and they are then copied into the
repository by hand and committed together:

  schema.sql  every table of `ads_l`, as SHOW CREATE TABLE gives it, sorted,
              with IF NOT EXISTS added and the AUTO_INCREMENT counter removed;
  SCHEMA.md   one section per table: columns and keys, what a row is, the
              section of METHOD.md or PATTERNS.md that defines it, the code
              that writes and reads it, the endpoints that publish it, the
              files of schema/ that created or changed it, and the service
              user's grants on it.

Written on 9 October 2026, when the tables had come to number 46 and the
hand-maintained schema.sql still described the ten of 3 October: since then
every change had gone into a dated file in schema/, so the only complete
description of the database was the database. Everything in SCHEMA.md except
the two hand-written lines per table (DESCRIPTIONS below) is derived: columns
and grants from the server, readers and writers from the SQL in the string
literals of the code, endpoints by following calls from the routes of app.py,
history from schema/*.sql and from git. So a table added without a
description, or a description left for a dropped table, is reported on
stderr rather than papered over, and so is a column the migrations do not
account for.
"""

import argparse
import ast
import datetime
import glob
import os
import re
import subprocess
import sys
from collections import defaultdict

DATABASE = "ads_l"
GENERATED_MARK = "generated by tools/schema_doc.py"

# ---------------------------------------------------------------------------
# Hand-written: what a row is and which section of the method defines it.
# Everything else in SCHEMA.md comes from the database and the code. Keep one
# entry per table; the script warns about a table without one and about an
# entry whose table is gone.

GROUPS = (
    ("live", "Monthly live counters",
     "Written by the service as packets arrive, every 15 minutes, and read by the statistics endpoints. "
     "Device addresses are kept only in `monthly_devices` and `monthly_sources`, for the current and the "
     "previous month (METHOD.md, section 9)."),
    ("archive", "Monthly archives and snapshots",
     "What is left of a month once its device addresses are deleted (`archive_loop` in sources.py, every "
     "six hours, for months older than the previous one), and the frozen copy of every statistics "
     "endpoint taken by nightly.py the night a month's last day is computed."),
    ("conspicuity", "Nightly: conspicuity family",
     "Computed by nightly.py at 01:30 UTC from the raw recording of the previous UTC day (METHOD.md, "
     "section 10) and written in one transaction, which first deletes the day's rows: a rerun of a day "
     "replaces it."),
    ("quality", "Nightly: data quality",
     "Part of the conspicuity family's transaction in nightly.py (FAMILIES), listed apart because it "
     "describes the feed rather than the aircraft."),
    ("patterns", "Nightly: patterns family",
     "How light aviation flies (PATTERNS.md), from the same nightly run, written in a second transaction "
     "of its own so that a failure in one family leaves the other's day written."),
    ("other", "Other",
     "Bookkeeping."),
)

DESCRIPTIONS = {
    # Monthly live counters
    "monthly_devices": dict(
        group="live", doc="METHOD.md 1, 9",
        row="An ADS-L, ADS-B or FLARM device address heard in a month, with its address type and last category: "
            "the ADS-L adoption chart. Addresses are deleted once the month is archived."),
    "monthly_sources": dict(
        group="live", doc="METHOD.md 1, 9",
        row="A device address heard in a month on one source (system) and channel (radio or net), with first "
            "and last time heard. Addresses are deleted once the month is archived."),
    "daily_visibility": dict(
        group="live", doc="METHOD.md 2",
        row="One 15-minute write of a day's visibility totals per source, channel and category. Append-only: "
            "readers sum the rows of a day, so the service needs no UPDATE on it."),
    "monthly_visibility_detail": dict(
        group="live", doc="METHOD.md 2-6",
        row="Visibility totals of a month per source, channel, category and height band above sea level and "
            "above ground: airborne time, segments, time without signal, age of fixes, disappearances, "
            "intervals, turn-rate and circling subsets. Added to in place (INSERT ... ON DUPLICATE KEY UPDATE)."),
    "monthly_visibility_grid": dict(
        group="live", doc="METHOD.md 3, 8",
        row="Visibility totals of a month per 0.25-degree cell, group of sources and channel. Added to in place."),
    "monthly_reception_pattern": dict(
        group="live", doc="METHOD.md 7",
        row="Radio packets received from circling aircraft in a month, per source, category, distance band and "
            "30-degree sector, with the SNR sums. Added to in place."),
    "monthly_prediction": dict(
        group="live", doc="METHOD.md 5",
        row="Errors of the position predicted over a horizon, per month, source, category, circling or not and "
            "predictor, as a histogram in bins b0 to b13 (edges in /api/prediction, bins_m) with count and sum. "
            "Added to in place."),
    "monthly_hours": dict(
        group="live", doc="METHOD.md 2, 8",
        row="Flying time of a month per category, each aircraft counted once whatever source or channel heard it. "
            "Added to in place."),
    # Monthly archives and snapshots
    "monthly_devices_summary": dict(
        group="archive", doc="METHOD.md 9",
        row="Devices of an archived month per address type prefix and category (255: none recorded): what is "
            "left of monthly_devices."),
    "monthly_sources_summary": dict(
        group="archive", doc="METHOD.md 9",
        row="Devices of an archived month per source, channel and category, and how many were heard on two "
            "different days: what is left of monthly_sources."),
    "monthly_return_summary": dict(
        group="archive", doc="METHOD.md 9",
        row="Of the devices heard on a source in a month, how many were heard on it again the month after "
            "(from 7 October 2026)."),
    "monthly_systems_summary": dict(
        group="archive", doc="METHOD.md 1, 9",
        row="Systems per aircraft for an archived month and category, as /api/systems publishes them "
            "(from 7 October 2026)."),
    "monthly_systems_combo_summary": dict(
        group="archive", doc="METHOD.md 1, 9",
        row="Aircraft of an archived month and category per combination of systems shared by at least 5 "
            "aircraft (from 7 October 2026)."),
    "monthly_circling_pilot_summary": dict(
        group="archive", doc="PATTERNS.md 2; METHOD.md 9",
        row="Pilots of an archived month per category, thermal-count band and decile of right-hand share: what "
            "is left of daily_circling_pilot."),
    "monthly_circling_preference": dict(
        group="archive", doc="PATTERNS.md 2; METHOD.md 9",
        row="The sums of the per-pilot circling preference test for an archived month, category and minimum "
            "number of thermals, from which the published figures follow."),
    "monthly_routes_summary": dict(
        group="archive", doc="PATTERNS.md 6; METHOD.md 9",
        row="Flights and distinct aircraft of an archived month per pair of airfields: what is left of "
            "daily_routes."),
    "monthly_snapshot": dict(
        group="archive", doc="METHOD.md 9 (Monthly snapshots)",
        row="What one statistics endpoint published for a month, frozen the night its last day was computed: "
            "zlib-compressed JSON with the commits of METHOD.md and of the code in force."),
    # Nightly, conspicuity
    "daily_drone_classes": dict(
        group="conspicuity", doc="METHOD.md 10.1",
        row="Addresses declaring a drone on a day per evidence class and flight class, with their airborne "
            "time, so that the page can say how many were set aside and why."),
    "daily_drones": dict(
        group="conspicuity", doc="METHOD.md 10.1",
        row="Drone flying time and aircraft on a day per evidence and flight class, 1-degree cell, height band, "
            "speed band and the systems the address was heard on."),
    "daily_drone_cells": dict(
        group="conspicuity", doc="METHOD.md 10.1",
        row="The same per cell only, so that distinct drones per cell can be read."),
    "daily_drone_extent": dict(
        group="conspicuity", doc="METHOD.md 10.1",
        row="Drones of a day by how far they went from the first fix of their largest session."),
    "daily_drone_encounters": dict(
        group="conspicuity", doc="METHOD.md 10.1, 10.2",
        row="Encounters of a day between a drone and a crewed aircraft (within 10 s, 1 km and 150 m), per "
            "evidence and flight class, cell, systems of each side, distance, closing speed and geometry."),
    "daily_crewed_encounters": dict(
        group="conspicuity", doc="METHOD.md 10.2",
        row="Encounters of a day between two crewed aircraft, per pair of kinds, threshold (wide or close), cell, "
            "distance band, closing band, geometry and the systems of each side."),
    "daily_air_cells": dict(
        group="conspicuity", doc="METHOD.md 10.2",
        row="Flying time and distinct aircraft of a day per kind and 0.25-degree cell over the fixes encounters "
            "are looked for in: the denominator of the crewed encounters."),
    "daily_same_aircraft_pairs": dict(
        group="conspicuity", doc="METHOD.md 10.2",
        row="Encounters of a day left out as probably one aircraft under two addresses, per pair of kinds and "
            "threshold, with the distinct address pairs."),
    "daily_parked": dict(
        group="conspicuity", doc="METHOD.md 10.3",
        row="Parked aircraft transmitting on a day per system and category: aircraft, seconds and packets."),
    # Nightly, quality
    "daily_quality": dict(
        group="quality", doc="METHOD.md 10.4",
        row="One check of a day for a system or an OGN receiver: how many of how many failed it, and the measured "
            "value where there is one. Receivers have a row only when flagged, plus one row per check named '*'."),
    # Nightly, patterns
    "daily_hours_solar": dict(
        group="patterns", doc="PATTERNS.md 1",
        row="Flying time and distinct aircraft of a UTC day per local date, category and local solar hour."),
    "daily_circling": dict(
        group="patterns", doc="PATTERNS.md 2",
        row="Thermals, degrees turned and seconds circling to each side on a day, per category."),
    "daily_circling_pilot": dict(
        group="patterns", doc="PATTERNS.md 2; METHOD.md 9",
        row="Thermals to each side per address and day, for the per-pilot preference test. Holds addresses: "
            "reduced to the monthly circling summaries and deleted once the month is archived."),
    "daily_gaggles": dict(
        group="patterns", doc="PATTERNS.md 2",
        row="Pairs of thermals flown together by two aircraft on a day, per pair of categories, turning the same "
            "way or opposite ways."),
    "daily_thermals": dict(
        group="patterns", doc="PATTERNS.md 3, 12",
        row="Thermals of a day per kind, terrain, solar hour, 1-degree cell, climb band and radius band, with the "
            "sums that give the means."),
    "daily_thermal_sites": dict(
        group="patterns", doc="PATTERNS.md 3",
        row="Thermals of a day per kind and 0.25-degree cell, by the take-off site of the flight they were flown "
            "in, for naming thermal places."),
    "daily_mixed_thermals": dict(
        group="patterns", doc="PATTERNS.md 3",
        row="Thermals of a day shared by two aircraft of different kinds, by median vertical separation."),
    "daily_agl_hours": dict(
        group="patterns", doc="PATTERNS.md 4, 12",
        row="Airborne time of a day per kind, terrain, solar hour and band of height above the ground."),
    "daily_circling_time": dict(
        group="patterns", doc="PATTERNS.md 5, 12",
        row="Seconds circling against airborne seconds on a day, per kind, terrain and solar hour."),
    "daily_flights": dict(
        group="patterns", doc="PATTERNS.md 6, 7, 12",
        row="Flights of a day per kind, terrain, launch method, start hour, duration band, extent band and path "
            "band, with seconds and path length."),
    "daily_flight_classes": dict(
        group="patterns", doc="PATTERNS.md 6",
        row="Flights of at least 2 minutes on a day per kind, terrain, class (local, out and return, cross, one "
            "way...), landing and distance and path bands."),
    "daily_routes": dict(
        group="patterns", doc="PATTERNS.md 6; METHOD.md 9",
        row="One-way flights of powered aircraft between two airfields per day and address. Holds addresses: "
            "reduced to monthly_routes_summary and deleted once the month is archived."),
    "daily_launches": dict(
        group="patterns", doc="PATTERNS.md 7, 12",
        row="Launches of gliders and hang gliders on a day per method, towed kind, terrain, 1-degree cell, height "
            "band and tow duration band."),
    "daily_tug_tows": dict(
        group="patterns", doc="PATTERNS.md 7",
        row="How many tugs towed how often on a day, by band of tows; never the tug's address."),
    "daily_wave": dict(
        group="patterns", doc="PATTERNS.md 8",
        row="Glider climbs of a day that are probably wave, per 1-degree cell."),
    "daily_cruise": dict(
        group="patterns", doc="PATTERNS.md 9",
        row="Level segments of powered aircraft and helicopters on a day per kind, ADS-B emitter category, "
            "altitude reference, altitude band and speed band."),
    "daily_helicopter_night": dict(
        group="patterns", doc="PATTERNS.md 10",
        row="Helicopter flying time and aircraft of a day per cell, night or day and band of height above "
            "the ground."),
    "daily_tug_time": dict(
        group="patterns", doc="PATTERNS.md 11",
        row="Tugs of a day by the share of their flying time spent towing; never the tug's address."),
    # Other
    "nightly_runs": dict(
        group="other", doc="METHOD.md 10",
        row="One nightly computation of a day: when it finished, how many hourly files it read and which were "
            "missing, lines read, duration, and which family failed if one did."),
}

# ---------------------------------------------------------------------------
# Database (read-only in practice: SHOW and information_schema only)


def load_settings(repo):
    """DB_USER and DB_PASSWORD from the checkout's .env, as nightly.py loads them."""
    try:
        from dotenv import load_dotenv
    except ImportError:
        return
    load_dotenv(os.path.join(repo, ".env"))


def connect():
    """As nightly.connect_db: .env if DB_USER is set, ~/.my.cnf otherwise."""
    import pymysql
    if os.getenv("DB_USER"):
        return pymysql.connect(host="localhost", user=os.getenv("DB_USER"), password=os.getenv("DB_PASSWORD"),
                               database=DATABASE, autocommit=True)
    return pymysql.connect(read_default_file=os.path.expanduser("~/.my.cnf"), database=DATABASE, autocommit=True)


def read_database(conn):
    db = {"tables": [], "create": {}, "columns": defaultdict(list), "indexes": defaultdict(dict)}
    with conn.cursor() as cur:
        cur.execute("SHOW VARIABLES LIKE 'version'")
        row = cur.fetchone()
        db["version"] = row[1] if row else "unknown"
        cur.execute("SHOW FULL TABLES")
        for name, kind in cur.fetchall():
            if kind == "BASE TABLE":
                db["tables"].append(name)
            else:
                db.setdefault("views", []).append(name)
        db["tables"].sort()
        for t in db["tables"]:
            cur.execute(f"SHOW CREATE TABLE `{t}`")
            db["create"][t] = cur.fetchone()[1]
        cur.execute(
            "SELECT TABLE_NAME, COLUMN_NAME, COLUMN_TYPE, IS_NULLABLE, COLUMN_DEFAULT "
            "FROM information_schema.COLUMNS WHERE TABLE_SCHEMA = %s ORDER BY TABLE_NAME, ORDINAL_POSITION",
            (DATABASE,))
        for t, c, typ, nullable, default in cur.fetchall():
            db["columns"][t].append({"name": c, "type": typ, "null": nullable == "YES", "default": default})
        cur.execute(
            "SELECT TABLE_NAME, INDEX_NAME, NON_UNIQUE, COLUMN_NAME FROM information_schema.STATISTICS "
            "WHERE TABLE_SCHEMA = %s ORDER BY TABLE_NAME, INDEX_NAME, SEQ_IN_INDEX", (DATABASE,))
        for t, index, non_unique, c in cur.fetchall():
            db["indexes"][t].setdefault(index, {"unique": not non_unique, "columns": []})["columns"].append(c)
        try:
            cur.execute("SHOW GRANTS FOR CURRENT_USER")
            db["grants"] = parse_grants(r[0] for r in cur.fetchall())
        except Exception as e:          # noqa: BLE001 -- grants are optional in the output
            db["grants"] = None
            warn(f"SHOW GRANTS FOR CURRENT_USER failed ({type(e).__name__}); SCHEMA.md will have no grants")
    return db


GRANT_RE = re.compile(r"^GRANT (?P<privs>.+?) ON (?P<obj>\S+) TO (?P<user>`[^`]*`@`[^`]*`|'[^']*'@'[^']*'|\S+)")


def parse_grants(lines):
    """Privileges per object, and the grantee. The rest of each line (which
    can carry IDENTIFIED BY PASSWORD and its hash) is dropped unread."""
    out = {"user": None, "objects": defaultdict(list)}
    for line in lines:
        m = GRANT_RE.match(line)
        if not m:
            continue
        out["user"] = m.group("user").replace("`", "'")
        obj = m.group("obj").replace("`", "")
        privs = [p.strip() for p in re.split(r",\s*(?![^()]*\))", m.group("privs"))]
        out["objects"][obj].extend(privs)
    return out


def grants_for(grants, table):
    if not grants:
        return None
    parts, wider = [], set()
    for obj, label in (("*.*", "server-wide"), (f"{DATABASE}.*", "database-wide"), (f"{DATABASE}.{table}", None)):
        privs = [p for p in grants["objects"].get(obj, []) if p != "USAGE" and p not in wider]
        wider.update(privs)
        if privs:
            parts.append(", ".join(privs) + (f" ({label})" if label else " (this table)"))
    return "; ".join(parts) if parts else "none"


# ---------------------------------------------------------------------------
# Code: which function names which table, and for what

TABLE_WORD = r"(?<![\w.])`?{t}`?(?![\w])"
WRITE_KW = r"(?:INSERT(?:\s+IGNORE)?\s+INTO|REPLACE\s+INTO|DELETE\s+FROM|UPDATE)\s+"
READ_KW = r"(?<!DELETE )(?<!DELETE\n)(?:FROM|JOIN)\s+"   # the FROM of a DELETE is not a read
GENERIC_WRITE = re.compile(WRITE_KW + r"\{")
GENERIC_READ = re.compile(READ_KW + r"\{")
# SQL keywords are matched in upper case only, as the code writes them, so
# that prose such as "read from daily_x" in a log message is not SQL.
SQL_TABLE = re.compile(r"(?:INSERT(?:\s+IGNORE)?\s+INTO|REPLACE\s+INTO|DELETE\s+FROM|UPDATE|FROM|JOIN)\s+`?([a-z_][a-z0-9_]*)`?")
TABLEISH = re.compile(r"^(?:daily|monthly|nightly)_[a-z0-9_]+$")


def docstrings(node):
    """The docstring nodes under node: prose, which names tables in English."""
    out = set()
    for n in ast.walk(node):
        if isinstance(n, (ast.Module, ast.ClassDef, ast.FunctionDef, ast.AsyncFunctionDef)) and n.body:
            first = n.body[0]
            if isinstance(first, ast.Expr) and isinstance(first.value, ast.Constant):
                out.add(id(first.value))
    return out


def string_values(node):
    """String literals under node, docstrings left out, f-strings rebuilt
    with {} for each field."""
    out = []
    skip = docstrings(node)
    for n in ast.walk(node):
        if id(n) in skip:
            continue
        if isinstance(n, ast.JoinedStr):
            out.append("".join(v.value if isinstance(v, ast.Constant) and isinstance(v.value, str) else "{}"
                               for v in n.values))
        elif isinstance(n, ast.Constant) and isinstance(n.value, str):
            out.append(n.value)
    return out


def names_used(node):
    out = set()
    for n in ast.walk(node):
        if isinstance(n, ast.Name):
            out.add(n.id)
        elif isinstance(n, ast.Attribute):
            out.add(n.attr)
    return out


def calls_made(node):
    out = set()
    for n in ast.walk(node):
        if isinstance(n, ast.Call):
            f = n.func
            if isinstance(f, ast.Name):
                out.add(f.id)
            elif isinstance(f, ast.Attribute):
                out.add(f.attr)
        # a bound method passed as a value (Thread(target=tracker.writer_loop), ("hours", self.hours_stats))
        if isinstance(n, ast.Attribute) and isinstance(n.ctx, ast.Load) and isinstance(n.value, ast.Name) \
                and n.value.id in ("self", "tracker", "sources"):
            out.add(n.attr)
    return out


def code_files(repo):
    files = [f for f in ("app.py", "sources.py", "nightly.py", "recorder.py") if os.path.exists(os.path.join(repo, f))]
    files += sorted(os.path.relpath(p, repo) for p in glob.glob(os.path.join(repo, "tools", "**", "*.py"), recursive=True)
                    if os.path.basename(p) != "schema_doc.py")
    files += sorted(os.path.relpath(p, repo) for p in glob.glob(os.path.join(repo, "tools", "**", "*.sh"), recursive=True))
    return files


def analyse_code(repo, tables):
    """Per table: {(file, function): set of 'read'/'write'/'ref'}; plus the
    functions of the service, their calls, and the routes of app.py."""
    refs = defaultdict(lambda: defaultdict(set))
    functions = {}            # (file, qualname) -> {"calls": set, "tables": {t: kinds}}
    routes = []               # (path, handler qualname)
    in_code = set()           # table-like names that the code uses in SQL
    patterns = {t: re.compile(TABLE_WORD.format(t=re.escape(t))) for t in tables}

    def kinds_in(strings, t):
        k = set()
        pat = patterns[t]
        for s in strings:
            if not pat.search(s):
                continue
            if re.search(WRITE_KW + r"`?" + re.escape(t) + r"`?(?![\w])", s):
                k.add("write")
            if re.search(READ_KW + r"`?" + re.escape(t) + r"`?(?![\w])", s):
                k.add("read")
            if s.strip("` ") == t:
                k.add("name")
        return k

    for rel in code_files(repo):
        path = os.path.join(repo, rel)
        text = open(path, encoding="utf-8").read()
        if rel.endswith(".sh"):
            for t in tables:
                if patterns[t].search(text):
                    refs[t][(rel, "")].add("write" if re.search(WRITE_KW + re.escape(t), text) else "ref")
            continue
        tree = ast.parse(text, rel)
        module_consts = {}     # NAME -> {table: kinds}
        consts_api = {}
        # Module functions that build a write statement around a table name
        # (sources._upsert): a constant made by calling one writes that table.
        builders = {n.name for n in tree.body if isinstance(n, ast.FunctionDef)
                    and any(GENERIC_WRITE.search(s) for s in string_values(n))}
        for node in tree.body:
            if isinstance(node, ast.Assign):
                strings = string_values(node.value)
                found = {t: kinds_in(strings, t) for t in tables if any(patterns[t].search(s) for s in strings)}
                if isinstance(node.value, ast.Call) and getattr(node.value.func, "id", None) in builders:
                    found = {t: (k - {"name"}) | {"write"} for t, k in found.items()}
                for target in node.targets:
                    if isinstance(target, ast.Name):
                        if found:
                            module_consts[target.id] = found
                        if isinstance(node.value, ast.Constant) and isinstance(node.value.value, str):
                            consts_api[target.id] = node.value.value
                for s in strings:
                    in_code.update(m.group(1) for m in SQL_TABLE.finditer(s) if TABLEISH.match(m.group(1)))
                    if TABLEISH.match(s):
                        in_code.add(s)

        def visit(node, qual):
            strings = string_values(node)
            used = names_used(node)
            generic_w = any(GENERIC_WRITE.search(s) for s in strings)
            generic_r = any(GENERIC_READ.search(s) for s in strings)
            found = {}
            for t in tables:
                k = kinds_in(strings, t)
                via_const = [module_consts[n][t] for n in used if n in module_consts and t in module_consts[n]]
                for ck in via_const:
                    k |= (ck - {"name"}) or {"name"}
                if not k:
                    continue
                if "name" in k:           # named as a value, used in SQL built around it
                    k.discard("name")
                    if generic_w:
                        k.add("write")
                    if generic_r:
                        k.add("read")
                    if not k:
                        k.add("ref")
                found[t] = k
                refs[t][(rel, qual)] |= k
            for s in strings:
                in_code.update(m.group(1) for m in SQL_TABLE.finditer(s) if TABLEISH.match(m.group(1)))
            functions[(rel, qual)] = {"calls": calls_made(node), "tables": found}

        for node in tree.body:
            if isinstance(node, (ast.FunctionDef, ast.AsyncFunctionDef)):
                visit(node, node.name)
                if rel == "app.py":
                    for d in node.decorator_list:
                        if isinstance(d, ast.Call) and getattr(d.func, "attr", None) == "route" and d.args:
                            routes.append((route_path(d.args[0], consts_api), node.name))
            elif isinstance(node, ast.ClassDef):
                for sub in node.body:
                    if isinstance(sub, (ast.FunctionDef, ast.AsyncFunctionDef)):
                        visit(sub, f"{node.name}.{sub.name}")
            elif isinstance(node, ast.If):     # if __name__ == "__main__": block
                strings = string_values(node)
                if any(patterns[t].search(s) for s in strings for t in tables):
                    visit(node, "__main__")
    return refs, functions, routes, in_code


def route_path(arg, consts):
    if isinstance(arg, ast.Constant):
        return arg.value
    if isinstance(arg, ast.BinOp) and isinstance(arg.op, ast.Add):
        return route_path(arg.left, consts) + route_path(arg.right, consts)
    if isinstance(arg, ast.Name):
        return consts.get(arg.id, "{" + arg.id + "}")
    return "?"


def endpoints_by_table(functions, routes):
    """Follow calls from each route of app.py through app.py and sources.py,
    by function name, and collect the tables read on the way."""
    by_name = defaultdict(list)
    for (rel, qual) in functions:
        if rel in ("app.py", "sources.py"):
            by_name[qual.split(".")[-1]].append((rel, qual))
    out = defaultdict(set)
    for path, handler in routes:
        seen, todo = set(), [("app.py", handler)]
        while todo:
            key = todo.pop()
            if key in seen or key not in functions:
                continue
            seen.add(key)
            f = functions[key]
            for t, kinds in f["tables"].items():
                if kinds & {"read", "ref"}:
                    out[t].add(path)
            for c in f["calls"]:
                todo.extend(by_name.get(c, ()))
    return out


def family_of_nightly(repo):
    """nightly.FAMILIES, read from the source without importing it."""
    path = os.path.join(repo, "nightly.py")
    if not os.path.exists(path):
        return {}
    for node in ast.parse(open(path, encoding="utf-8").read()).body:
        if isinstance(node, ast.Assign) and any(isinstance(t, ast.Name) and t.id == "FAMILIES" for t in node.targets):
            fam = ast.literal_eval(node.value)
            return {t: name for name, ts in fam.items() for t in ts}
    return {}


# ---------------------------------------------------------------------------
# Migrations and the hand-written schema.sql they started from

COL_DEF = re.compile(r"^\s*`(\w+)`\s+(.+?),?\s*$")


def column_type(defn):
    """`int(10) unsigned NOT NULL DEFAULT 0` -> `int(10) unsigned`."""
    m = re.match(r"((?:enum|set)\([^)]*\)|\w+(?:\([^)]*\))?(?:\s+unsigned)?(?:\s+zerofill)?)", defn.strip(), re.I)
    return m.group(1).lower() if m else defn.strip().lower()


def parse_creates(sql):
    """{table: {column: type}} from the CREATE TABLE statements of sql."""
    out = {}
    for m in re.finditer(r"CREATE TABLE(?: IF NOT EXISTS)? `(\w+)` \((.*?)\n\)", sql, re.S):
        cols = {}
        for line in m.group(2).splitlines():
            c = COL_DEF.match(line)
            if c:
                cols[c.group(1)] = column_type(c.group(2))
        out[m.group(1)] = cols
    return out


def strip_comments(sql):
    return "\n".join(l for l in sql.splitlines() if not l.lstrip().startswith("--"))


def parse_migration(sql):
    """[(table, action, detail)] with action create/alter/grant, and the
    column changes [(table, 'add'|'modify'|'drop', column, type)]."""
    body = strip_comments(sql)
    events, changes = [], []
    for t, cols in parse_creates(body).items():
        events.append((t, "create", f"{len(cols)} columns"))
        changes.append((t, "create", None, dict(cols)))
    for m in re.finditer(r"ALTER TABLE `(\w+)`(.*?);", body, re.S):
        t, clause = m.group(1), m.group(2)
        what = []
        for a in re.finditer(r"ADD COLUMN `(\w+)` ([^,;]+?)(?:\s+AFTER `\w+`)?\s*(?:,|$)", clause):
            changes.append((t, "add", a.group(1), column_type(a.group(2))))
            what.append(f"adds {a.group(1)}")
        for a in re.finditer(r"MODIFY(?: COLUMN)? `(\w+)` ([^,;]+?)\s*(?:,|$)", clause):
            changes.append((t, "modify", a.group(1), column_type(a.group(2))))
            what.append(f"changes {a.group(1)} to {column_type(a.group(2))}")
        for a in re.finditer(r"DROP COLUMN `(\w+)`", clause):
            changes.append((t, "drop", a.group(1), None))
            what.append(f"drops {a.group(1)}")
        if re.search(r"ADD PRIMARY KEY", clause):
            what.append("new primary key")
        events.append((t, "alter", ", ".join(what) or "alters"))
    for m in re.finditer(r"GRANT (.+?) ON `?\w+`?\.`?(\w+)`? TO", body):
        events.append((m.group(2), "grant", m.group(1)))
    return events, changes


def git(repo, *args):
    try:
        r = subprocess.run(["git", "-C", repo] + list(args), capture_output=True, text=True, timeout=60)
        return r.stdout if r.returncode == 0 else ""
    except (OSError, subprocess.SubprocessError):
        return ""


def migrations_in_order(repo):
    """schema/*.sql in the order they were committed, which is the order
    they were applied: the file names sort otherwise within a day
    (2026-10-07-crewed-encounters.sql widens a column of a table that
    2026-10-07-nightly.sql, committed earlier, creates). Files not yet
    committed come last, by name."""
    def key(path):
        rel = os.path.relpath(path, repo)
        added = git(repo, "log", "--diff-filter=A", "--format=%ct", "--", rel).split()
        return (int(added[-1]) if added else float("inf"), rel)
    return sorted(glob.glob(os.path.join(repo, "schema", "*.sql")), key=key)


def handwritten_baseline(repo):
    """The last hand-maintained schema.sql in git: (sha, date, sql), or None.
    Tables older than schema/ (3 October 2026) were described only there."""
    for line in git(repo, "log", "--format=%h %ad", "--date=short", "--", "schema.sql").splitlines():
        sha, date = line.split()
        sql = git(repo, "show", f"{sha}:schema.sql")
        if sql and GENERATED_MARK not in sql:
            return sha, date, sql
    return None


def baseline_origin(repo, table):
    """The commit that added table's CREATE to the hand-written schema.sql."""
    out = git(repo, "log", "--reverse", "--format=%h %ad", "--date=short", "-S",
              f"CREATE TABLE IF NOT EXISTS `{table}`", "--", "schema.sql").split("\n")
    return out[0].strip() if out and out[0].strip() else None


# ---------------------------------------------------------------------------
# Output

warnings = []


def warn(msg):
    warnings.append(msg)
    print(f"warning: {msg}", file=sys.stderr)


def render_schema_sql(db, today, commit):
    out = [
        f"-- Schema of the Electronic Conspicuity Monitor, {GENERATED_MARK} on {today}",
        f"-- from the production database `{DATABASE}` (MariaDB {db['version']}), code at {commit}.",
        "-- Do not edit: change the database through a dated file in schema/, then run",
        "--   cd ~/ads-l-map && python3 tools/schema_doc.py --out ~/schemadoc",
        "-- and commit this file and SCHEMA.md as it writes them. SCHEMA.md says what each",
        "-- table holds and which code reads and writes it.",
        "--",
        "-- Each table as SHOW CREATE TABLE gives it, with IF NOT EXISTS added and the",
        "-- AUTO_INCREMENT counter removed. Load it on an empty server with",
        "--   mysql < schema.sql",
        "-- then create the service user and its grants as README.md describes.",
        "",
        f"CREATE DATABASE IF NOT EXISTS {DATABASE} CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci;",
        f"USE {DATABASE};",
        "",
    ]
    for t in db["tables"]:
        ddl = re.sub(r"\s+AUTO_INCREMENT=\d+", "", db["create"][t])
        ddl = ddl.replace("CREATE TABLE ", "CREATE TABLE IF NOT EXISTS ", 1)
        out.append(ddl + ";")
        out.append("")
    return "\n".join(out)


def md_escape(s):
    return str(s).replace("|", "\\|")


def fmt_functions(keys):
    """[(file, function)] -> "`file` `f`, `g`; `other` `h`", one group per file."""
    by_file = defaultdict(list)
    for rel, qual in keys:
        by_file[rel].append(qual)
    return "; ".join(f"`{rel}`" + (" " + ", ".join(f"`{q}`" for q in quals if q) if any(quals) else "")
                     for rel, quals in by_file.items())


def program_of(rel):
    if rel in ("app.py", "sources.py"):
        return "service"
    if rel == "nightly.py":
        return "nightly"
    if rel == "recorder.py":
        return "recorder"
    return "one-off tool"


def render_schema_md(db, ctx, today, commit):
    refs, routes_by_table, families = ctx["refs"], ctx["endpoints"], ctx["families"]
    history, baseline, origins = ctx["history"], ctx["baseline"], ctx["origins"]
    grants = db.get("grants")
    group_of = {t: DESCRIPTIONS.get(t, {}).get("group", "undescribed") for t in db["tables"]}
    out = [
        "# Database schema",
        "",
        f"Generated by `tools/schema_doc.py` on {today} from the production database `{DATABASE}` "
        f"(MariaDB {db['version']}) and the code at `{commit}`. Do not edit it by hand: run the script again "
        "after each migration, as README.md describes, and commit it with `schema.sql`.",
        "",
        "Everything here is read from the database or the code except the line that says what a row is and the "
        "section of the method that defines it, which are kept in `DESCRIPTIONS` in the script. Columns and keys "
        "come from `information_schema`. Writers and readers are the functions whose SQL names the table, "
        "directly or through a constant or a list of table names (`nightly.FAMILIES`, the archive steps of "
        "`sources.py`). Endpoints are found by following calls from each route of `app.py` through `app.py` and "
        "`sources.py`. History lists the files of `schema/` that create, alter or grant on the table; tables "
        "older than that directory were described only in the hand-written `schema.sql`, whose commit is given. "
        "In the column tables, *PK* is the column's position in the primary key.",
        "",
        "Every `day` column is the UTC day of the recording the row was computed from; every `month` is "
        "`YYYY-MM`. `lat_idx` and `lon_idx` are `floor(lat * n)` and `floor(lon * n)`, with n = 4 for "
        "0.25-degree cells and 1 for 1-degree cells, and -32768 for rows with no place.",
        "",
    ]
    if grants:
        out += ["## The service user's grants", ""]
        out.append(f"As `SHOW GRANTS FOR CURRENT_USER` returned them for {grants['user']}, the user the service, "
                   "nightly.py and this script run as:")
        out.append("")
        for obj in sorted(grants["objects"]):
            privs = [p for p in grants["objects"][obj] if p != "USAGE"]
            if privs:
                out.append(f"- `{obj}`: {', '.join(privs)}")
        out.append("")
    out += ["## Contents", ""]
    for key, title, _ in GROUPS + (("undescribed", "Not described yet", ""),):
        ts = [t for t in db["tables"] if group_of[t] == key]
        if ts:
            out.append(f"- {title} ({len(ts)}): " + ", ".join(f"[`{t}`](#{t})" for t in ts))
    out.append("")
    for key, title, intro in GROUPS + (("undescribed", "Not described yet",
                                        "Tables with no entry in DESCRIPTIONS in tools/schema_doc.py."),):
        ts = [t for t in db["tables"] if group_of[t] == key]
        if not ts:
            continue
        out += [f"## {title}", "", intro, ""]
        for t in ts:
            out += render_table(t, db, refs.get(t, {}), routes_by_table.get(t, set()), families.get(t),
                                history.get(t, []), baseline, origins.get(t), grants)
    return "\n".join(out).rstrip() + "\n"


def render_table(t, db, trefs, endpoints, family, hist, baseline, origin, grants):
    d = DESCRIPTIONS.get(t, {})
    out = [f"### `{t}`", ""]
    out.append(d.get("row", "*No description.*"))
    out.append("")
    pk = []
    for name, ix in db["indexes"].get(t, {}).items():
        if name == "PRIMARY":
            pk = ix["columns"]
    out += ["| Column | Type | Default | PK |", "|---|---|---|---|"]
    for c in db["columns"].get(t, []):
        typ = c["type"] + (" NULL" if c["null"] else "")
        default = "" if c["default"] is None else c["default"]
        pos = str(pk.index(c["name"]) + 1) if c["name"] in pk else ""
        out.append(f"| `{c['name']}` | {md_escape(typ)} | {md_escape(default)} | {pos} |")
    out.append("")
    facts = []
    others = [(n, ix) for n, ix in db["indexes"].get(t, {}).items() if n != "PRIMARY"]
    if others:
        facts.append("Other indexes: " + "; ".join(
            f"`{n}` ({', '.join(ix['columns'])}){' unique' if ix['unique'] else ''}" for n, ix in others))
    facts.append("Defined in: " + (d.get("doc") or "*not given*"))
    writers = sorted(k for k, v in trefs.items() if "write" in v)
    readers = sorted(k for k, v in trefs.items() if "read" in v and "write" not in v)
    readwrite = sorted(k for k, v in trefs.items() if "read" in v and "write" in v)
    mentions = sorted(k for k, v in trefs.items() if v == {"ref"})
    core_writers = [k for k in writers if program_of(k[0]) != "one-off tool"]
    if core_writers:
        by_prog = defaultdict(list)
        for k in core_writers:
            by_prog[program_of(k[0])].append(k)
        facts.append("Written by: " + "; ".join(f"the {p}, {fmt_functions(ks)}" for p, ks in by_prog.items())
                     + (f" (nightly family `{family}`)" if family else ""))
    else:
        facts.append("Written by: *no code in this repository*")
    rs = [k for k in readers + readwrite if program_of(k[0]) != "one-off tool"]
    if rs:
        facts.append("Read by: " + fmt_functions(sorted(rs)))
    if endpoints:
        facts.append("Published through: " + ", ".join(f"`{e}`" for e in sorted(endpoints)))
    tool_w = sorted(k for k in writers if program_of(k[0]) == "one-off tool")
    tool_r = sorted(k for k in readers + mentions if program_of(k[0]) == "one-off tool")
    if tool_w:
        facts.append("Changed after the fact by one-off tools: " + fmt_functions(tool_w))
    if tool_r:
        facts.append("Read or named by one-off tools: " + fmt_functions(tool_r))
    hist_parts = []
    if origin:
        sha, _, date = origin.partition(" ")
        hist_parts.append(f"added to the hand-written `schema.sql` in `{sha}`" + (f" ({date})" if date else ""))
    for f, action, detail in hist:
        if action == "grant":
            continue
        hist_parts.append(f"`{f}` ({'created' if action == 'create' else detail})")
    granted = sorted({f for f, a, _ in hist if a == "grant"})
    facts.append("History: " + ("; ".join(hist_parts) if hist_parts else "*not in any migration*")
                 + (f". Grants in {', '.join(f'`{g}`' for g in granted)}" if granted else ""))
    g = grants_for(grants, t)
    if g is not None:
        facts.append(f"Service user's privileges: {g}")
    out += [f"- {f}" for f in facts]
    out.append("")
    return out


def main():
    ap = argparse.ArgumentParser(description=__doc__.split("\n")[0])
    ap.add_argument("--out", required=True, help="directory for schema.sql and SCHEMA.md (created if missing)")
    ap.add_argument("--repo", default=None,
                    help="the service's checkout (default: the directory above this script if it holds app.py, "
                         "otherwise the current directory)")
    args = ap.parse_args()
    here = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
    repo = os.path.abspath(args.repo or (here if os.path.exists(os.path.join(here, "app.py")) else os.getcwd()))
    if not os.path.exists(os.path.join(repo, "app.py")):
        sys.exit(f"{repo} is not a checkout of the monitor (no app.py)")
    out_dir = os.path.abspath(os.path.expanduser(args.out))
    if out_dir == repo or out_dir.startswith(repo + os.sep):
        sys.exit("--out must be outside the checkout, which deploy.sh owns")

    load_settings(repo)
    conn = connect()
    try:
        db = read_database(conn)
    finally:
        conn.close()

    today = datetime.date.today().isoformat()
    commit = git(repo, "rev-parse", "--short", "HEAD").strip() or "unknown"
    tables = db["tables"]

    refs, functions, routes, in_code = analyse_code(repo, tables)
    endpoints = endpoints_by_table(functions, routes)
    families = family_of_nightly(repo)

    history, expected = defaultdict(list), {}
    base = handwritten_baseline(repo)
    origins = {}
    if base:
        sha, date, sql = base
        for t, cols in parse_creates(sql).items():
            expected[t] = dict(cols)
            origins[t] = baseline_origin(repo, t) or f"{sha} {date}"
    else:
        warn("no hand-written schema.sql in git history: tables older than schema/ have no baseline")
    for path in migrations_in_order(repo):
        name = "schema/" + os.path.basename(path)
        events, changes = parse_migration(open(path, encoding="utf-8").read())
        for t, action, detail in events:
            history[t].append((name, action, detail))
        for t, op, c, typ in changes:
            if op == "create":            # CREATE TABLE IF NOT EXISTS: a no-op on a table that exists
                expected.setdefault(t, typ)
                continue
            cols = expected.setdefault(t, {})
            if op == "drop":
                cols.pop(c, None)
            else:
                cols[c] = typ

    # Checks, on stderr
    for t in tables:
        if t not in DESCRIPTIONS:
            warn(f"table {t} has no entry in DESCRIPTIONS")
        elif DESCRIPTIONS[t]["group"] in ("conspicuity", "patterns", "quality") and t not in families:
            warn(f"{t} is described as nightly ({DESCRIPTIONS[t]['group']}) but is not in nightly.FAMILIES")
        elif t in families and DESCRIPTIONS[t]["group"] not in (families[t], "quality"):
            warn(f"{t} is in nightly family {families[t]} but described as {DESCRIPTIONS[t]['group']}")
    for t in DESCRIPTIONS:
        if t not in tables:
            warn(f"DESCRIPTIONS has {t}, which is not in the database")
    core = {t for t in tables if any(program_of(rel) != "one-off tool" for rel, _ in refs.get(t, {}))}
    for t in tables:
        if t not in core:
            warn(f"table {t} is not referenced by app.py, sources.py, nightly.py or recorder.py"
                 + (" (only by one-off tools)" if refs.get(t) else ""))
    for t in sorted(in_code - set(tables)):
        warn(f"the code names table {t} in SQL, and the database has no such table")
    for t in tables:
        if t not in expected:
            warn(f"table {t} is in no migration and not in the hand-written schema.sql")
            continue
        have = {c["name"]: c["type"].lower() for c in db["columns"][t]}
        want = expected[t]
        for c in have.keys() - want.keys():
            warn(f"drift: {t}.{c} ({have[c]}) is in the database and in no migration")
        for c in want.keys() - have.keys():
            warn(f"drift: {t}.{c} is in the migrations and not in the database")
        for c in have.keys() & want.keys():
            if have[c] != want[c]:
                warn(f"drift: {t}.{c} is {have[c]} in the database, {want[c]} in the migrations")

    ctx = {"refs": refs, "endpoints": endpoints, "families": families, "history": history,
           "baseline": base, "origins": origins}
    sql = render_schema_sql(db, today, commit)
    md = render_schema_md(db, ctx, today, commit)
    # The files carry DDL and metadata only; refuse to write if a secret slipped in.
    secret = os.getenv("DB_PASSWORD")
    for name, text in (("schema.sql", sql), ("SCHEMA.md", md)):
        if (secret and secret in text) or re.search(r"IDENTIFIED BY|PASSWORD\s*'|^\s*INSERT\s", text, re.I | re.M):
            sys.exit(f"{name} would contain a credential or data; nothing written")
    os.makedirs(out_dir, exist_ok=True)
    for name, text in (("schema.sql", sql), ("SCHEMA.md", md)):
        with open(os.path.join(out_dir, name), "w", encoding="utf-8") as f:
            f.write(text)
    groups = defaultdict(int)
    for t in tables:
        groups[DESCRIPTIONS.get(t, {}).get("group", "undescribed")] += 1
    print(f"{len(tables)} tables (" + ", ".join(f"{k} {v}" for k, v in groups.items()) + f"), "
          f"{len(warnings)} warnings; wrote {out_dir}/schema.sql and SCHEMA.md")
    return 0


if __name__ == "__main__":
    sys.exit(main())
